### ISSUE TITLE
Create A Template Gallery

### ISSUE THREAD

**Issue by zeroSteiner** [securestate/king-phisher-templates#13]
It would be great to have a `gallery.md` markdown file which would contain screenshots from a new `screenshots` branch in this repo or something similar of all of the templates. This would make it easier for users new and experience alike to quickly see what template they may want to use.

**Comment by zeroSteiner** [comment]
PRs #14 and #15 have added images for this. Still waiting on a markdown / rst document to tie them all together.

**Comment by wolfthefallen** [comment]
Completed with PR #17
