### ISSUE TITLE
Landing page display problemes

### ISSUE THREAD

**Issue by Itrustsecurity** [securestate/king-phisher-templates#18]
Hi , 
i've diploy the landing page website (Shell/Anti-Virus_Update) on  /var/www path 
i've test the Url --> work successfully
when i send the Url to clients, the âge doesnt get and display the company parameters like : 
{{ client.company_name }} ,  {{ time.local...,  
see attached file
![landinf page antivirus update](https://cloud.githubusercontent.com/assets/18242158/14244663/314b7dca-fa54-11e5-9cdb-8d6caaaf52b0.PNG)

**Comment by zeroSteiner** [comment]
This is a duplicate of securestate/king-phisher#94.

**Comment by Itrustsecurity** [comment]
i think you didn't undrstand me , i've made changes as mentionned on the README.md pour on this file the company name and  other variables changes are not mentioned : {{ client.company_name }} , {{ time.local..
I wanted to know if those variables are retreived automatically or i must change them manually

**Comment by zeroSteiner** [comment]
See my [comment](https://github.com/securestate/king-phisher/issues/94#issuecomment-205280299). The templates not rendering is indicative of a larger problem relating to your setup.
