### ISSUE TITLE
Export an outlook email to Html and send it by KP

### ISSUE THREAD

**Issue by Itrustsecurity** [securestate/king-phisher-templates#19]
Hello,
i've prepare an email on outlook, and i want to send the same email with the same texte format contents (signature)
I export the email to html with outlook save as option, when i try to use the email and send it by using KP, it return an error, is there any tool to convert outlook (html) emails to KP format,

**Comment by zeroSteiner** [comment]
The King Phisher message format is HTML, it's just enhanced with templating from the Jinja 2 engine. I was not able to reproduce this problem. My guess is that if the HTML is looking invalid when loaded as a message template it is probably due to the complexity used by outlook. You should try to remove unnecessary HTML and then reload it into King Phisher.

**Comment by Itrustsecurity** [comment]
Thank you i'ev tried to copy the html outlook code on KP html email editor, i've just a probleme how can i  add an attached email to email signature,  i mean i've a logo to be added to the signature and it must be sended as attached file , how can i attache it ,

**Comment by zeroSteiner** [comment]
Read the wiki on how to [embed images into messages](https://github.com/securestate/king-phisher/wiki/Creating-Message-Content#embedding-images-into-messages). I recommend the second technique, the local one.

**Comment by Itrustsecurity** [comment]
I'm using the second technique but how can i apply some html format on the image
ex : 

[Uploading imageformat.txt…]()

**Comment by zeroSteiner** [comment]
The jinja function inserts it's own `img` tag. If you want to add formatting you need to do something that wraps the `img` tag / `inline_image` function.

**Comment by Itrustsecurity** [comment]
can you take a look at the sended txt file

**Comment by zeroSteiner** [comment]
No I can not. This is an issue with your HTML and not an issue with King Phisher itself. I can't help you create your template, we have plenty of resources and references to help you. Look through the wiki in the King Phisher repo and the example templates in this repo.

If you run into an issue with King Phisher itself then we can talk.
