### ISSUE TITLE
Reset Statistics

### ISSUE THREAD

**Issue by bucky67gto** [securestate/king-phisher-templates#33]
Is there a way to reset the statistics for a campaign without creating a new campaign.

for example I ran a test and want to keep the settings, but remove the test data?

not a huge issue, but would make it quicker to implement tests and live engagements

**Comment by zeroSteiner** [comment]
Easiest way would be to delete all of the messages that were sent as part of the campaign. Each time a message is deleted, the associated visits are deleted as well. You should be able to use the shift key and select multiple messages, then right click and delete.

**Comment by wolfthefallen** [comment]
Just as a side note and friendly reminder:
- All template issues should be posted on this GitHub Repository.
- For any issues using plugins please use the [King Phisher Plugin Repository](https://github.com/securestate/king-phisher-plugins)
- For all other issues please use the main [King Phisher](https://github.com/securestate/king-phisher) GitHub repository for questions or issues.

**Comment by zeroSteiner** [comment]
I'm going to close this issue out due to inactivity. If you're still experiencing it, please respond to the preceding message in this thread and we'll re-open it. Thanks.
